### ISSUE TITLE
Corrupt ranks

### ISSUE THREAD

**Issue by Ankeraout** [ClassiCube/MCGalaxy#186]
Our server crashed when the admin created a rank, and it did not restart until I removed some lines from ranks properties file. Here is the crash stack trace :

Type: NotSupportedException
Source: mscorlib
Message: The given path's format is not supported.
Target: Init
Trace:    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at MCGalaxy.PlayerList.Load(String path)
   at MCGalaxy.Group..ctor(LevelPermission Perm, Int32 maxB, Int64 maxUn, String fullName, Char newColor, String motd, String file, Byte maps, String prefix)
   at MCGalaxy.GroupProperties.AddGroup(Group& grp, Int32 version)
   at MCGalaxy.GroupProperties.InitAll()
   at MCGalaxy.Group.InitAll()
   at MCGalaxy.Server.LoadAllSettings()
   at MCGalaxy.Server.Start()
   at MCGalaxy.Gui.Window.<Window_Load>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by MissingChunkOfficial** [comment]
Yes, TMC had this error. 
-Donkeh - TheMissingChunk Owner

**Comment by UnknownShadow200** [comment]
Don't create ranks which have / \ : ? " < > | in their names or filenames.

**Comment by Ankeraout** [comment]
The rank had only letters in its name.

**Comment by UnknownShadow200** [comment]
Only ascii letters, none of those other fancy characters? Those fancy characters did not save to rank.properties properly in 1.8.7.2, but fixed if you are using the latest commits.

**Comment by Ankeraout** [comment]
You can ask Donkeh, the rank was named "Meme"
