### ISSUE TITLE
Weird crash

### ISSUE THREAD

**Issue by lavacraft1** [ClassiCube/MCGalaxy#283]
=== crash occurred ===
Time: 10/19/2016 2:19:52 PM
Running on: .NET 2.0.50727.5485, Windows - 6.1.7601.65536
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ClassicalSharp.StringBuffer.DeleteAt(Int32 index)
   at ClassicalSharp.Gui.Widgets.TextInputWidget.DeleteChar()
   at ClassicalSharp.Gui.Widgets.TextInputWidget.BackspaceKey(Boolean controlDown)
   at ClassicalSharp.Gui.Widgets.TextInputWidget.HandlesKeyDown(Key key)
   at ClassicalSharp.Gui.Screens.ChatScreen.HandlesKeyDown(Key key)
   at ClassicalSharp.Gui.Screens.HudScreen.HandlesKeyDown(Key key)
   at ClassicalSharp.InputHandler.KeyDownHandler(Object sender, KeyboardKeyEventArgs e)
   at OpenTK.Input.KeyboardDevice.set_Item(Key key, Boolean value)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   at OpenTK.Platform.Windows.API.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   at OpenTK.GameWindow.Run()
   at ClassicalSharp.DesktopWindow.ClassicalSharp.IPlatformWindow.Run()
   at ClassicalSharp.Program.RunMultiplayer(String[] args, Boolean nullContext, Int32 width, Int32 height)
   at ClassicalSharp.Program.Main(String[] args)

-- Using Direct3D9 api --
Adapter: AMD Radeon HD 7480D
Mode: HardwareVertexProcessing
Texture memory: 1760 MB
Max 2D texture dimensions: 16384
Depth buffer format: D24X8
Back buffer format: X8R8G8B8

**Comment by lavacraft1** [comment]
I got that crash when i was holding back space after the first letter of my friends name (i was trying to get rid of the prefix and title)

**Comment by UnknownShadow200** [comment]
Fixed in the client https://github.com/UnknownShadow200/ClassicalSharp/commit/c781af2d853352860729d62133f6de36bb8aac01
