### ISSUE TITLE
Server restart-crash due to gun cmd

### ISSUE THREAD

**Issue by Goodlyay** [ClassiCube/MCGalaxy#449]
----5/26/2017 2:02:53 AM ----
Type: NullReferenceException
Source: MCGalaxy_
Message: Object reference not set to an instance of an object.
Target: DoPhysicsBlockchange
Trace:    at MCGalaxy.Level.DoPhysicsBlockchange(Int32 b, Byte block, Boolean overRide, PhysicsArgs data, Byte extBlock, Boolean addUndo)
   at MCGalaxy.Commands.Fun.CmdGun.DoShoot(Player p, Byte type, Byte extType)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

-------------------------

Not sure EXACTLY what happened but I know some guy was using /gun in the grief map when this happened. Caused a restart and then crash.

**Comment by UnknownShadow200** [comment]
@Goodlyay 
Reproducible or once off?

**Comment by Goodlyay** [comment]
Can't reproduce.

**Comment by UnknownShadow200** [comment]
Well I still can't see why the original crash occurred.

But my WIP changes in how critical tasks (fly, aim, gun, missile, ride) work, to use a safe scheduler task instead of creating their own threads, means if an unhandled exception occurs with them now will simply log an error, instead of taking down the whole server.
