### ISSUE TITLE
SQL Error

### ISSUE THREAD

**Issue by skititlez** [ClassiCube/MCGalaxy#522]
Follow up to #521 
looks like there is a slight issue with the 6.9 im still using the same old version as the classic server but it looks this pretains to that sql V

Heres the error message
----11/27/2019 9:54:42 PM----
Type: FileLoadException
Source: MCGalaxy_
Message: Could not load file or assembly 'MySql.Data, Version=6.9.8.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Target: CreateConnection
Trace:    at MCGalaxy.SQL.MySQLBackend.CreateConnection()
   at MCGalaxy.SQL.SqlQuery.Iterate(String sql, Object[] parameters, Object arg, ReaderCallback callback)
   at MCGalaxy.SQL.Database.Do(String sql, Boolean createDB, Object arg, ReaderCallback callback, Object[] args)

**Comment by UnknownShadow200** [comment]
Try deleting mysql.data.dll so it gets redownloaded
