### ISSUE TITLE
Rare error thrown when undoing

### ISSUE THREAD

**Issue by UnknownShadow200** [ClassiCube/MCGalaxy#548]
Happened several times on NA2
```
Message: Object reference not set to an instance of an object.
Target: Dispose
Trace:    at MCGalaxy.Util.IReaderWriterLock.SlimLock.Dispose()
   at MCGalaxy.Drawing.Ops.DrawOpPerformer.DrawOpOutputter.Output(DrawOpBlock b)
   at MCGalaxy.Drawing.Ops.UndoDrawOp.PerformUndo()
   at MCGalaxy.Drawing.Ops.UndoDrawOp.Perform(Vec3S32[] marks, Brush brush, DrawOpOutput output)
   at MCGalaxy.Drawing.Ops.DrawOpPerformer.Execute(Player p, DrawOp op, Brush brush, Vec3S32[] marks)
   at MCGalaxy.Drawing.Ops.DrawOpPerformer.ProcessDrawOps(Player p)
   at MCGalaxy.Drawing.Ops.DrawOpPerformer.DoQueuedDrawOp(Player p, DrawOp op, Brush brush, Vec3S32[] marks)
   at MCGalaxy.Drawing.Ops.DrawOpPerformer.Do(DrawOp op, Brush brush, Player p, Vec3S32[] marks, Boolean checkLimit)
   at MCGalaxy.Commands.Building.CmdUndo.UndoLastDrawOp(Player p)
   at MCGalaxy.Player.UseCommand(Command command, String message, CommandData data)
```

```
Trace:    at MCGalaxy.Util.IReaderWriterLock.SlimLock.Dispose()
   at MCGalaxy.Drawing.Ops.DrawOpPerformer.DrawOpOutputter.Output(DrawOpBlock b)
   at MCGalaxy.Drawing.Ops.UndoDrawOp.PerformUndo()
   at MCGalaxy.Drawing.Ops.UndoDrawOp.Perform(Vec3S32[] marks, Brush brush, DrawOpOutput output)
   at MCGalaxy.Drawing.Ops.DrawOpPerformer.Execute(Player p, DrawOp op, Brush brush, Vec3S32[] marks)
   at MCGalaxy.Drawing.Ops.DrawOpPerformer.ProcessDrawOps(Player p)
   at MCGalaxy.Drawing.Ops.DrawOpPerformer.DoQueuedDrawOp(Player p, DrawOp op, Brush brush, Vec3S32[] marks)
   at MCGalaxy.Drawing.Ops.DrawOpPerformer.Do(DrawOp op, Brush brush, Player p, Vec3S32[] marks, Boolean checkLimit)
   at MCGalaxy.Commands.Building.CmdUndo.UndoSelf(Player p, TimeSpan delta)
   at MCGalaxy.Commands.Building.CmdUndo.Use(Player p, String message, CommandData data)
   at MCGalaxy.Player.UseCommand(Command command, String message, CommandData data)
```

**Comment by UnknownShadow200** [comment]
66b89c9eea676d2dc0fd05e1f39819a4de98915a
