### ISSUE TITLE
[MySQL] BlockInfo failing to Insert/Select & "COLLATE NOCASE" on WhoWas Query does not execute properly

### ISSUE THREAD

**Issue by Venom983** [ClassiCube/MCGalaxy#65]
The below is only for CmdAbout:

Type: MySqlException
Source: MySql.Data
Message: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
Target: ReadPacket
Trace:    at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int32& insertedId)
   at MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int32& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at MCGalaxy.SQL.MySQL.fill(String queryString, DataTable toReturn) in C:\MCGalaxy-master\Database\MySQL.cs:line 87
   at MCGalaxy.SQL.Database.fillData(String queryString, Boolean skipError) in C:\MCGalaxy-master\Database\Database.cs:line 299

**Comment by Venom983** [comment]
This may help in the meantime: https://github.com/Hetal728/MCGalaxy/pull/68

**Comment by Venom983** [comment]
Resolving patch has been submitted. Issue no longer applicable.
