### ISSUE TITLE
about command showing nobody altering block

### ISSUE THREAD

**Issue by skititlez** [ClassiCube/MCGalaxy#82]
As the title states.
It seems to be happening on the server whenever we use /b or /about.
I went ahead and gave it a new database thinking it was due to an old MCforge database issue and it would still display unaltered blocks even if it is old.
The error in the console is

Type: MySqlException
Source: MySql.Data
Message: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"Blockmap179" WHERE X=210 AND Y=63 AND Z=122' at line 1
Target: ReadPacket
Trace:    at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int32& insertedId)
   at MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int32& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at MCGalaxy.SQL.MySQL.fill(String queryString, DataTable toReturn)
   at MCGalaxy.SQL.Database.fillData(String queryString, Boolean skipError)

**Comment by ghost** [comment]
Interesting. I'll look into it. I guess a temporary fix would be switching to SQLite. (Recommended since classic is so small these days)

Could you define "display unalterered blocks?"

**Comment by UnknownShadow200** [comment]
Are you using 1.7.3.0, or did you compile the latest commit?

According to a little birdy (aka venom983), this problem only occurs with 1.7.3.0 and not in the latest commit.

**Comment by skititlez** [comment]
@Hetal728 Here is a screenshot http://puu.sh/lYBCv.png
@UnknownShadow200 1.7.3.0 ill download the latest commit and check it.

**Comment by skititlez** [comment]
Checked with the latest commit. Seems to be doing the same thing. So unless i did something wrong, which is a high possibility (id10t error), i am stumped.

**Comment by UnknownShadow200** [comment]
What happens when you try with SQLite though?

I'll try later on my VM which has mysql installed.

**Comment by skititlez** [comment]
Yeah so it was a id10t error on my end. I had my co-hoster give me a hand with this one. Appears that the latest commit does resolve the issue.
